name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: nix build .#docker-image

      - name: Push docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_TOKEN" | nix develop --command crane auth login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
          nix develop --command crane push result ghcr.io/a-h/depot:${{ github.ref_name }}
          nix develop --command crane push result ghcr.io/a-h/depot:latest
